export type IconName =
  | "calendar-day"
  | "checkbox"
  | "check-circle"
  | "list-check"
  | "lock"
  | "pen-clip"
  | "plus"
  | "text-box-edit"
  | "trash"
  | "unlock"
  | "user"
  | "sort-alt"
  | "filter"
  | "search"
  | "dots"
  | "sort-alpha-up"
  | "sort-alpha-down"
  | "folder-download"
  | "arrow-left"
  | "sign-out"
  | "paper-plane-top"
  | "cross"
  | "eye"
  | "eye-crossed";

